# palabras compuestas se separan con puntos
# t odo en minusculas sin caracteres especiales
# siempre empieza con letra
# nombre con valor

config.puerto.servidor=8090
otra=algun valor
config.texto.ambiente=Configuración de ambiente de desarrollo
config.autor.nombre=Josué
config.autor.email=arleyjmartinez19@gmail.com